export const browserCoreExamples = [
  "elysiaclaw browser status",
  "elysiaclaw browser start",
  "elysiaclaw browser stop",
  "elysiaclaw browser tabs",
  "elysiaclaw browser open https://example.com",
  "elysiaclaw browser focus abcd1234",
  "elysiaclaw browser close abcd1234",
  "elysiaclaw browser screenshot",
  "elysiaclaw browser screenshot --full-page",
  "elysiaclaw browser screenshot --ref 12",
  "elysiaclaw browser snapshot",
  "elysiaclaw browser snapshot --format aria --limit 200",
  "elysiaclaw browser snapshot --efficient",
  "elysiaclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "elysiaclaw browser navigate https://example.com",
  "elysiaclaw browser resize 1280 720",
  "elysiaclaw browser click 12 --double",
  'elysiaclaw browser type 23 "hello" --submit',
  "elysiaclaw browser press Enter",
  "elysiaclaw browser hover 44",
  "elysiaclaw browser drag 10 11",
  "elysiaclaw browser select 9 OptionA OptionB",
  "elysiaclaw browser upload /tmp/elysiaclaw/uploads/file.pdf",
  'elysiaclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "elysiaclaw browser dialog --accept",
  'elysiaclaw browser wait --text "Done"',
  "elysiaclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "elysiaclaw browser console --level error",
  "elysiaclaw browser pdf",
];
